# Generated by Django 5.0.4 on 2024-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclass',
            name='largeContent',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
