# Generated by Django 5.0.4 on 2024-05-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_user_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='response',
            field=models.CharField(default='', max_length=100),
        ),
    ]
