# Generated by Django 5.0.4 on 2024-05-28 13:44

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
